# ?????? ?? ??
spring:
  datasource:
    # ?? ?? DB ?? ????
    url: jdbc:mysql://localhost:3306/dodutch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ljw3530

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true

# Kakao OAuth2 Configuration
kakao:
  client-id: 10465b286770cf6059972c6fe9f6cff1
  redirect-url: http://localhost:8080/api/users/login/oauth/kakao

# JWT Configuration
jwt:
  secret-key: 9kL2mN5pQ8rS1tU4vW7xY0zA3bC6dE9fG2hJ5kM8nP1qR4sT7uV0wX3yZ6aB9cD